/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beohoang98.qlhs.ui.dialog;

import com.beohoang98.qlhs.entities.Course;
import com.beohoang98.qlhs.services.CourseService;
import com.beohoang98.qlhs.services.MarkService;
import com.beohoang98.qlhs.ui.messages.Messages;
import com.beohoang98.qlhs.utils.Popup;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.schedulers.Schedulers;
import java.time.ZoneOffset;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/** @author noobcoder */
public class AddReCheck extends javax.swing.JDialog {

  /** Creates new form AddReCheck */
  public AddReCheck(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    courseList = new javax.swing.JList<>();
    jPanel2 = new javax.swing.JPanel();
    checkAll = new javax.swing.JButton();
    check = new javax.swing.JButton();
    uncheck = new javax.swing.JButton();
    uncheckAll = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    chosenList = new javax.swing.JList<>();
    jPanel3 = new javax.swing.JPanel();
    submit = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    toPicker = new com.github.lgooddatepicker.components.DatePicker();
    fromPicker = new com.github.lgooddatepicker.components.DatePicker();
    jLabel1 = new javax.swing.JLabel();
    jPanel6 = new javax.swing.JPanel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    addContainerListener(
        new java.awt.event.ContainerAdapter() {
          public void componentAdded(java.awt.event.ContainerEvent evt) {
            formComponentAdded(evt);
          }
        });

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    courseList.setModel(new DefaultListModel<Course>());
    jScrollPane2.setViewportView(courseList);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jScrollPane2, gridBagConstraints);

    jPanel2.setLayout(new java.awt.GridLayout(0, 1));

    checkAll.setText(">>");
    checkAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    checkAll.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkAllActionPerformed(evt);
          }
        });
    jPanel2.add(checkAll);

    check.setText(">");
    check.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    check.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkActionPerformed(evt);
          }
        });
    jPanel2.add(check);

    uncheck.setText("<");
    uncheck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    uncheck.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            uncheckActionPerformed(evt);
          }
        });
    jPanel2.add(uncheck);

    uncheckAll.setText("<<");
    uncheckAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    uncheckAll.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            uncheckAllActionPerformed(evt);
          }
        });
    jPanel2.add(uncheckAll);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.2;
    jPanel1.add(jPanel2, gridBagConstraints);

    chosenList.setModel(new DefaultListModel<Course>());
    jScrollPane1.setViewportView(chosenList);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jScrollPane1, gridBagConstraints);

    submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajax-loader.gif"))); // NOI18N
    submit.setText("Tạo");
    submit.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel3Layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(submit)));
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submit));

    jLabel2.setText("Đến ngày");

    jLabel1.setText("Từ ngày");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel5Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel5Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(
                                jLabel2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jLabel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                95,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel5Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                fromPicker,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                toPicker,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel5Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel5Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(
                                fromPicker,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel5Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                39,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                toPicker,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));

    jComboBox1.setModel(new DefaultComboBoxModel<String>());

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("locale_vi"); // NOI18N
    jLabel3.setText(bundle.getString("tab.class")); // NOI18N

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel6Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jComboBox1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        97,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel6Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel6Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jComboBox1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                    .addContainerGap()));

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(
                        jPanel6,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addGap(247, 247, 247)
                    .addComponent(
                        jPanel5,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addContainerGap()));
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel4Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        jPanel4Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                jPanel5,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                jPanel4Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jPanel6,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(
                                jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jPanel3,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jPanel4,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jPanel4,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jPanel3,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void uncheckAllActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_uncheckAllActionPerformed
    DefaultListModel<String> chosenModel = (DefaultListModel) chosenList.getModel();
    DefaultListModel<String> courseModel = (DefaultListModel) courseList.getModel();
    for (String code : Collections.list(courseModel.elements())) {
      chosenModel.removeElement(code);
      courseModel.addElement(code);
    }
  } // GEN-LAST:event_uncheckAllActionPerformed

  private void checkActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_checkActionPerformed
    List<Course> selectedList = courseList.getSelectedValuesList();
    DefaultListModel<Course> chosenModel = (DefaultListModel) chosenList.getModel();
    DefaultListModel<Course> courseModel = (DefaultListModel) courseList.getModel();
    for (Course course : selectedList) {
      chosenModel.addElement(course);
      courseModel.removeElement(course);
    }
  } // GEN-LAST:event_checkActionPerformed

  private void uncheckActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_uncheckActionPerformed
    List<Course> selectedList = chosenList.getSelectedValuesList();
    DefaultListModel<Course> chosenModel = (DefaultListModel) chosenList.getModel();
    DefaultListModel<Course> courseModel = (DefaultListModel) courseList.getModel();
    for (Course course : selectedList) {
      chosenModel.removeElement(course);
      courseModel.addElement(course);
    }
  } // GEN-LAST:event_uncheckActionPerformed

  private void submitActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_submitActionPerformed
    Date fromDate = Date.from(fromPicker.getDate().atStartOfDay().toInstant(ZoneOffset.UTC));
    Date toDate = Date.from(toPicker.getDate().atStartOfDay().toInstant(ZoneOffset.UTC));
    DefaultListModel<Course> chosenModel = (DefaultListModel) chosenList.getModel();

    if (fromDate == null || toDate == null) {
      return;
    }
    if (chosenModel.size() == 0) {
      return;
    }
    List<String> courseCodeList =
        Collections.list(chosenModel.elements()).stream()
            .map(course -> course.getCode())
            .collect(Collectors.toList());

    submit.setIcon(new ImageIcon("ajax-loader.gif"));
    Single.fromCallable(() -> MarkService.createReCheck(courseCodeList, fromDate, toDate))
        .subscribeOn(Schedulers.io())
        .observeOn(Schedulers.single())
        .doFinally(
            () -> {
              submit.setIcon(null);
            })
        .subscribe(
            (rechecks) -> {
              Popup.on(rootPane).info(Messages.t("create.success"));
              dispose();
            },
            this::showError);
  } // GEN-LAST:event_submitActionPerformed

  private void checkAllActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_checkAllActionPerformed
    DefaultListModel<String> chosenModel = (DefaultListModel) chosenList.getModel();
    DefaultListModel<String> courseModel = (DefaultListModel) courseList.getModel();
    for (String code : Collections.list(courseModel.elements())) {
      courseModel.removeElement(code);
      chosenModel.addElement(code);
    }
  } // GEN-LAST:event_checkAllActionPerformed

  private void formComponentAdded(
      java.awt.event.ContainerEvent evt) { // GEN-FIRST:event_formComponentAdded
    Single.fromCallable(() -> CourseService.getAllCourses())
        .subscribeOn(Schedulers.io())
        .observeOn(Schedulers.single())
        .subscribe(
            (courses) -> {
              DefaultListModel<Course> courseModel = (DefaultListModel) courseList.getModel();
              courseModel.addAll(courses);
            },
            this::showError);
  } // GEN-LAST:event_formComponentAdded

  void showError(Throwable throwable) {
    Popup.on(this).error(throwable);
  }

  /** @param args the command line arguments */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AddReCheck.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AddReCheck.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AddReCheck.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AddReCheck.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          public void run() {
            AddReCheck dialog = new AddReCheck(new javax.swing.JFrame(), true);
            dialog.addWindowListener(
                new java.awt.event.WindowAdapter() {
                  @Override
                  public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                  }
                });
            dialog.setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton check;
  private javax.swing.JButton checkAll;
  private javax.swing.JList<Course> chosenList;
  private javax.swing.JList<Course> courseList;
  private com.github.lgooddatepicker.components.DatePicker fromPicker;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton submit;
  private com.github.lgooddatepicker.components.DatePicker toPicker;
  private javax.swing.JButton uncheck;
  private javax.swing.JButton uncheckAll;
  // End of variables declaration//GEN-END:variables
}
