/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beohoang98.qlhs.ui.dialog;

import com.beohoang98.qlhs.entities.Student;
import com.beohoang98.qlhs.services.StudentService;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.schedulers.Schedulers;
import java.util.concurrent.TimeUnit;
import org.jetbrains.annotations.NotNull;

/** @author noobcoder */
public class AddStudent extends javax.swing.JDialog {
  Student student;
  AddHandler addHandler;

  /** Creates new form AddStudent */
  public AddStudent(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    mssvField = new javax.swing.JFormattedTextField();
    loading = new javax.swing.JLabel();
    searchBtn = new javax.swing.JButton();
    errorLabel = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cmndField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    genderField = new javax.swing.JComboBox<>();
    jPanel4 = new javax.swing.JPanel();
    addBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Thêm sinh viên");
    setPreferredSize(new java.awt.Dimension(400, 232));
    setSize(new java.awt.Dimension(0, 0));

    jPanel2.setBackground(java.awt.SystemColor.controlDkShadow);
    jPanel2.setMinimumSize(new java.awt.Dimension(148, 100));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
    flowLayout1.setAlignOnBaseline(true);
    jPanel2.setLayout(flowLayout1);

    jLabel1.setLabelFor(mssvField);
    jLabel1.setText("MSSV");
    jPanel2.add(jLabel1);

    mssvField.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
            new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    mssvField.setPreferredSize(new java.awt.Dimension(100, 32));
    jPanel2.add(mssvField);

    loading.setDisabledIcon(
        new javax.swing.ImageIcon(getClass().getResource("/ajax-loader.gif"))); // NOI18N
    loading.setOpaque(true);
    jPanel2.add(loading);

    searchBtn.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/icons8-search-24.png"))); // NOI18N
    searchBtn.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchBtnActionPerformed(evt);
          }
        });
    jPanel2.add(searchBtn);

    errorLabel.setForeground(new java.awt.Color(255, 102, 102));
    jPanel2.add(errorLabel);

    getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

    jPanel3.setLayout(new java.awt.BorderLayout());

    jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    jPanel5.setPreferredSize(new java.awt.Dimension(248, 150));
    jPanel5.setLayout(new java.awt.GridLayout(0, 2, 8, 8));

    jLabel2.setLabelFor(nameField);
    jLabel2.setText("Tên");
    jPanel5.add(jLabel2);

    nameField.setEditable(false);
    jPanel5.add(nameField);

    jLabel3.setLabelFor(cmndField);
    jLabel3.setText("CMND");
    jPanel5.add(jLabel3);

    cmndField.setEditable(false);
    jPanel5.add(cmndField);

    jLabel4.setText("Giới tính");
    jPanel5.add(jLabel4);

    genderField.setEditable(false);
    genderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"MALE", "FEMALE"}));
    genderField.setSelectedIndex(-1);
    jPanel5.add(genderField);

    jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

    addBtn.setText("Thêm");
    addBtn.setEnabled(false);
    addBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    addBtn.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            addBtnActionPerformed(evt);
          }
        });
    jPanel4.add(addBtn);

    jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

    getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  public void setAddHandler(AddHandler addHandler) {
    this.addHandler = addHandler;
  }

  private void addBtnActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_addBtnActionPerformed
    if (addHandler != null) {
      addHandler.onAdd(student);
      dispose();
    }
  } // GEN-LAST:event_addBtnActionPerformed

  private void searchBtnActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_searchBtnActionPerformed
    Long mssv = (Long) mssvField.getValue();
    loading.setEnabled(false);
    searchBtn.setEnabled(false);
    addBtn.setEnabled(false);
    errorLabel.setText("");
    Single.fromCallable(() -> StudentService.findByMSSV(mssv.intValue()))
        .delay(1, TimeUnit.SECONDS)
        .subscribeOn(Schedulers.io())
        .observeOn(Schedulers.single())
        .doFinally(
            () -> {
              loading.setEnabled(true);
              searchBtn.setEnabled(true);
            })
        .subscribe(
            studentOpt -> {
              if (studentOpt.isPresent()) {
                student = studentOpt.get();
                nameField.setText(student.getName());
                cmndField.setText(student.getCmnd());
                genderField.setSelectedItem(student.getGender().name());
                addBtn.setEnabled(true);
              } else {
                errorLabel.setText("Không tìm thấy");
              }
            },
            (t) -> {
              errorLabel.setText(t.getMessage());
            });
  } // GEN-LAST:event_searchBtnActionPerformed

  /** @param args the command line arguments */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AddStudent.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AddStudent.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AddStudent.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AddStudent.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          public void run() {
            AddStudent dialog = new AddStudent(new javax.swing.JFrame(), true);
            dialog.addWindowListener(
                new java.awt.event.WindowAdapter() {
                  @Override
                  public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                  }
                });
            dialog.setVisible(true);
          }
        });
  }

  public static interface AddHandler {
    void onAdd(@NotNull Student student);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBtn;
  private javax.swing.JTextField cmndField;
  private javax.swing.JLabel errorLabel;
  private javax.swing.JComboBox<String> genderField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JLabel loading;
  private javax.swing.JFormattedTextField mssvField;
  private javax.swing.JTextField nameField;
  private javax.swing.JButton searchBtn;
  // End of variables declaration//GEN-END:variables
}
