/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.beohoang98.qlhs.ui.tabs;

import com.beohoang98.qlhs.entities.Course;
import com.beohoang98.qlhs.entities.SchoolClass;
import com.beohoang98.qlhs.services.CourseService;
import com.beohoang98.qlhs.services.SchoolClassService;
import com.beohoang98.qlhs.utils.Popup;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.schedulers.Schedulers;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import org.hibernate.Hibernate;

/** @author noobcoder */
public class ReCheckList extends javax.swing.JPanel {

  String classCode;

  /** Creates new form ReCheckList */
  public ReCheckList() {
    initComponents();
  }

  public static void main(String[] args) {
    JFrame frame = new JFrame();
    frame.add(new ReCheckList());
    frame.pack();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox1 = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    addCheck = new javax.swing.JButton();
    comboBoxCourses = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    comboBoxClass = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    table = new com.beohoang98.qlhs.ui.components.DataTable();

    jComboBox1.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    addAncestorListener(
        new javax.swing.event.AncestorListener() {
          public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            formAncestorAdded(evt);
          }

          public void ancestorMoved(javax.swing.event.AncestorEvent evt) {}

          public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {}
        });

    addCheck.setText("Tạo phúc khảo mới");
    addCheck.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            addCheckActionPerformed(evt);
          }
        });

    comboBoxCourses.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxCoursesActionPerformed(evt);
          }
        });

    jLabel1.setText("Môn");

    comboBoxClass.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxClassActionPerformed(evt);
          }
        });

    jLabel2.setText("Lớp");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addCheck)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        comboBoxClass,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        comboBoxCourses,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCheck)
                            .addComponent(
                                comboBoxCourses,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(
                                comboBoxClass,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                    .addContainerGap(15, Short.MAX_VALUE)));

    table.addAncestorListener(
        new javax.swing.event.AncestorListener() {
          public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            tableAncestorAdded(evt);
          }

          public void ancestorMoved(javax.swing.event.AncestorEvent evt) {}

          public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {}
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(
                                table, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                            .addComponent(
                                jPanel2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jPanel2,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addContainerGap()));
  } // </editor-fold>//GEN-END:initComponents

  void mapClassToComboxBox(List<SchoolClass> classes) {
    for (SchoolClass schoolClass : classes) {
      comboBoxClass.addItem(schoolClass.getCode());
    }
  }

  private void addCheckActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_addCheckActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_addCheckActionPerformed

  private void tableAncestorAdded(
      javax.swing.event.AncestorEvent evt) { // GEN-FIRST:event_tableAncestorAdded
    // TODO add your handling code here:
  } // GEN-LAST:event_tableAncestorAdded

  private void comboBoxClassActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_comboBoxClassActionPerformed
    comboBoxCourses.removeAllItems();
    JComboBox<String> combo = (JComboBox<String>) evt.getSource();
    classCode = (String) combo.getSelectedItem();
    Single.fromCallable(() -> CourseService.getByClass(classCode))
        .subscribeOn(Schedulers.io())
        .observeOn(Schedulers.single())
        .subscribe(this::mapCourseToComboBox, this::showError);
  } // GEN-LAST:event_comboBoxClassActionPerformed

  void mapCourseToComboBox(List<Course> courses) {
    for (Course course : courses) {
      comboBoxCourses.addItem(course);
    }
  }

  private void comboBoxCoursesActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_comboBoxCoursesActionPerformed
    Course course = (Course) comboBoxCourses.getSelectedItem();
    Hibernate.initialize(course.getReChecks());
    Single.fromCallable(() -> course.getReChecks()).subscribe(table::setData, this::showError);
  } // GEN-LAST:event_comboBoxCoursesActionPerformed

  private void formAncestorAdded(
      javax.swing.event.AncestorEvent evt) { // GEN-FIRST:event_formAncestorAdded
    comboBoxClass.removeAllItems();
    System.out.println("Loading...");
    Single.fromCallable(() -> SchoolClassService.findAll(false))
        .subscribeOn(Schedulers.io())
        .observeOn(Schedulers.single())
        .subscribe(this::mapClassToComboxBox, this::showError);
  } // GEN-LAST:event_formAncestorAdded

  void showError(Throwable throwable) {
    Popup.on(this).error(throwable);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addCheck;
  private javax.swing.JComboBox<String> comboBoxClass;
  private javax.swing.JComboBox<Course> comboBoxCourses;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel2;
  private com.beohoang98.qlhs.ui.components.DataTable table;
  // End of variables declaration//GEN-END:variables
}
