/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.beohoang98.qlhs;

import com.beohoang98.qlhs.utils.HBUtils;

import org.hibernate.Session;

import java.io.IOException;

public class App {
  public static void main(String[] args) throws IOException {
    Session session = HBUtils.getSessionFactory().openSession();
    session.close();
  }
}
