/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.beohoang98.qlhs;

import com.beohoang98.qlhs.utils.HBUtils;

import java.io.IOException;

public class App {
  public static void main(String[] args) throws IOException {
    Runtime.getRuntime().addShutdownHook(new ShutdownHook());
  }

  public static class ShutdownHook extends Thread {
    @Override
    public void run() {
      HBUtils.down();
    }
  }
}
