/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.beohoang98.qlhs;

import com.beohoang98.qlhs.utils.HBUtils;

import org.hibernate.SessionFactory;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertTrue;

public class AppTest {
  @Test
  public void hbUtilsShouldDown() throws IOException {
    SessionFactory factory = HBUtils.getSessionFactory();
    assertTrue(factory.isOpen());
    HBUtils.down();
    assertTrue(factory.isClosed());
  }
}
